goapi:
    name: goapi
    image:
        repository: grethinam/goapi
        tag: latest
        pullPolicy: Always
        imagePullSecrets: mydockerhubregistrykey
    type: LoadBalancer
    containerPort: 3000

goweb:
    name: goweb
    image:
        repository: grethinam/goweb
        tag: latest
        pullPolicy: Always
        imagePullSecrets: mydockerhubregistrykey
    type: LoadBalancer
    containerPort: 8080
    
mysql:
    name: mysqldb
    image:
        repository: grethinam/my-mysql
        tag: latest
        pullPolicy: Always
        imagePullSecrets: mydockerhubregistrykey
    type: ClusterIP
    containerPort: 3306
