# Default values for helmapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3


goapi:
    name: goapi
    image:
        repository: grethinam/goapi
        tag: latest
        pullPolicy: Always
        imagePullSecrets: mydockerhubregistrykey
    type: LoadBalancer
    containerPort: 3000
    
ingress:
  enabled: false
  
service:
      type: LoadBalancer
      port: 3000