apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: grethinam/my-mysql:latest
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: mydockerhubregistrykey